### ISSUE TITLE
Also scan for embedded plugins and apps

### ISSUE THREAD

**Issue by helje5** [ZeeZide/5GUIs#1]
Several apps carry additional apps in their `Frameworks` folder, e.g.:
```
Zini18:~ helge$ ls -d /Applications/zoom.us.app/Contents/Frameworks/*.app
/Applications/zoom.us.app/Contents/Frameworks/CptHost.app
/Applications/zoom.us.app/Contents/Frameworks/Transcode.app
/Applications/zoom.us.app/Contents/Frameworks/ZMScreenshot.app
/Applications/zoom.us.app/Contents/Frameworks/ZoomUninstaller.app
/Applications/zoom.us.app/Contents/Frameworks/caphost.app
```

We should scan those as well and incorporate into the result. The `ExecutableFileTechnologyInfo` is prepared for that already.

**Comment by sarnau** [comment]
Docker is another example. It is a modern AppKit Swift app, but in reality it also has an embedded Docker Desktop.app, which is Electron based.

**Comment by helje5** [comment]
Docker is also special, because it (better) puts the stuff in MacOS, not Frameworks:
```
Zini18:~ helge$ ls -la /Applications/Docker.app/Contents/MacOS/
total 272656
-rwxr-xr-x   1 helge  admin  14461904 Sep 28 22:56 Docker
drwxr-xr-x   3 helge  admin        96 Sep 28 22:56 Docker Desktop.app
-rwxr-xr-x   1 helge  admin  21371872 Sep 28 22:56 com.docker.backend
```

**Comment by helje5** [comment]
OK got this, at least for apps. Not scanning for plugins yet. (and Zoom seems to be native indeed?!)
