### ISSUE TITLE
Dropbox detected as AppKit ObjC app, it is JavaScript

### ISSUE THREAD

**Issue by sarnau** [ZeeZide/5GUIs#9]
Tungsten.framework in the "Framework" bundle points to "Tungsten Fabric" as the API

**Comment by sarnau** [comment]
Also seems to be Python based? Weird collection of frameworks and APIs

**Comment by helje5** [comment]
Maybe this should check for `Frameworks/python-extensions` to collect .python as a language.

I don't know what Tungsten is, another Electron? Or something Dropbox specific?

**Comment by sarnau** [comment]
Never heard of it before [https://tungsten.io](url)

**Comment by sarnau** [comment]
Seems networking related.

**Comment by helje5** [comment]
Should now get detected as Python. Though I think you are right, the app itself I think is Electron now. Probably part of some nested bundle which we need to detect via Issue #1 .

**Comment by sarnau** [comment]
Ok, I found this article [https://www.pythonpeople.nl/how-python-powers-dropbox/](url) => so, yes it should report as Python.

**Comment by helje5** [comment]
As both. Python + Electron, we can do combi texts! :-) But the latter is pending Issue #1

**Comment by helje5** [comment]
OK, closing this, the other thing needs to be done as part of #1
